/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  api: [
    {
      type: "doc",
      id: "api/README",
    },
    {
      type: "doc",
      id: "api/authentication",
    },
    {
      type: "category",
      label: "Endpoints",
      collapsed: false,
      collapsible: false,
      items: require("./docs/api/sidebar.ts")
    }
  ],
  guides: [
    {
      type: "autogenerated",
      dirName: "guides"
    }
  ]
};

export default sidebars;