{
 "openapi": "3.0.1",
 "info": {
  "title": "Template Api",
  "version": "1.0"
 },
 "servers": [
  {
   "url": "https://api.sandbox.fortressapi.com/"
  }
 ],
 "paths": {
  "/api/trust/v1/assets": {
   "post": {
    "tags": [
     "Assets"
    ],
    "summary": "Create the asset. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "get": {
    "tags": [
     "Assets"
    ],
    "summary": "Retrieve a list of assets for specific organization. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/assets/{id}": {
   "get": {
    "tags": [
     "Assets"
    ],
    "summary": "Retrieve the asset by id (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "patch": {
    "tags": [
     "Assets"
    ],
    "summary": "Patch the asset. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/auth/endpoints-permissions-tree": {
   "get": {
    "tags": [
     "Auth"
    ],
    "summary": "Retrieve full tree of endpoints permissions"
   }
  },
  "/api/v1/private-cross-service/auth/global-enabled-endpoints-permissions": {
   "get": {
    "tags": [
     "Auth"
    ],
    "summary": "Retrieve global enabled endpoints permissions"
   }
  },
  "/api/v1/private-cross-service/auth/enabled-endpoints-permissions-for-api-user/{authId}": {
   "get": {
    "tags": [
     "Auth"
    ],
    "summary": "Retrieve enabled endpoints permissions for api user"
   }
  },
  "/api/v1/private-cross-service/auth/default-auth-identifier/{orgId}": {
   "get": {
    "tags": [
     "Auth"
    ],
    "summary": "Retrieves auth identifier by organization id"
   }
  },
  "/api/trust/v1/available-transfer-methods": {
   "get": {
    "tags": [
     "AvailableTransferMethods"
    ],
    "summary": "Retrieve a list with available transfer methods. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/organization/v1/current-organization": {
   "get": {
    "tags": [
     "CurrentOrganization"
    ],
    "summary": "Retrieve the current organization. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "patch": {
    "tags": [
     "CurrentOrganization"
    ],
    "summary": "Update the current organization. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/organization/v1/current-organization/readonly": {
   "post": {
    "tags": [
     "CurrentOrganization"
    ],
    "summary": "Create a read-only user. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/organization/v1/current-organization/webhook-config": {
   "get": {
    "tags": [
     "CurrentOrganization"
    ],
    "summary": "Retrieve the webhook configuration. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "patch": {
    "tags": [
     "CurrentOrganization"
    ],
    "summary": "Patch the current webhook config. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/custodial-accounts": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve custodial accounts by identity identifier. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create the new custodial account."
   }
  },
  "/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/fiat-deposit-instructions/{assetFiatType}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the fiat deposit instructions."
   }
  },
  "/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/crypto-deposit-instructions/{network}/{assetFiatType}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the crypto deposit instructions."
   }
  },
  "/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the custodial account by its id."
   },
   "patch": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Update account status"
   }
  },
  "/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/rename-with-label": {
   "patch": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Update account name and label."
   }
  },
  "/api/trust/v1/custodial-accounts": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create the new custodial account. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the filtered, paged list with custodial accounts. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the custodial account by id. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "patch": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Update account status (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/fiat-deposit-instructions/{assetFiatType}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the fiat deposit instructions. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/crypto-deposit-instructions/{network}/{assetFiatType}": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the crypto deposit instructions. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/balances": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the custodial account balances. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-wire": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create an incoming wire simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/sandbox/start-incoming-wire-bulk": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create an incoming wire simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-ach": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create an incoming ach simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-check": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create incoming check deposit simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-ach-withdrawal": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Create an incoming ach withdrawal simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/withdraw-crypto": {
   "post": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Withdraw crypto. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{accountId}/beneficiaries": {
   "put": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Overwrite beneficiaries for an account (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Retrieve the collection of account beneficiaries (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/rename": {
   "patch": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Update account name (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/{custodialAccountId}/label": {
   "patch": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Update custodial account label (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/custodial-accounts/agreement": {
   "get": {
    "tags": [
     "CustodialAccounts"
    ],
    "summary": "Get custodial account agreement (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/security-admin/v1/endpoints-permissions-tree": {
   "get": {
    "tags": [
     "EndpointsPermissionsTree"
    ],
    "summary": "Retrieve hierarchy of endpoint access permissions (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/endpoints-permissions-tree/{id}": {
   "patch": {
    "tags": [
     "EndpointsPermissionsTree"
    ],
    "summary": "Patches endpoint access permission tree node (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/v1/private-cross-service/external-accounts": {
   "get": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Retrieve external accounts by identity identifier. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/external-accounts/financial": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ]
   }
  },
  "/api/v1/private-cross-service/external-accounts/wire": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Create the external wire account."
   }
  },
  "/api/v1/private-cross-service/external-accounts/international-wire": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Create a new international wire"
   }
  },
  "/api/trust/v1/external-accounts/{externalAccountId}": {
   "get": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Retrieve specific external account by id. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/external-accounts": {
   "get": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Retrieve the filtered, paged list with external accounts. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/external-accounts/financial/widget-url/{identityId}": {
   "get": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Retrieve the widget Url for particular identity. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/external-accounts/financial": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Create a funds transfer method and the respective external account. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/external-accounts/wire": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Create the external wire account. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/external-accounts/international-wire": {
   "post": {
    "tags": [
     "ExternalAccounts"
    ],
    "summary": "Create a new international wire (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/identities/{identityId}/external-accounts": {
   "get": {
    "tags": [
     "Identities"
    ]
   }
  },
  "/api/v1/private-cross-service/identities/{identityId}/custodial-accounts": {
   "get": {
    "tags": [
     "Identities"
    ]
   }
  },
  "/api/v1/private-cross-service/identities/{identityId}/widget-url": {
   "get": {
    "tags": [
     "Identities"
    ]
   }
  },
  "/api/internal-admin/v1/organizations": {
   "get": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retrieve the organizations. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/organizations/{organizationId}": {
   "get": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retrieve the organization. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/{organizationId}/sync-auth0": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Sync org metadata with Auth0. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/sync-auth0": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Sync all orgs metadata with Auth0. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/organizations/{organizationId}/inactivate-provider-specific/{provider}": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Inactivate ProviderSpecific Accounts. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/organizations/{organizationId}/custodial-account": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Create the new custodial account without age validation. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/ensure-system-accounts": {
   "patch": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Ensure system custodial account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-liquidity-provider-account": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Top up internal omnibus from Liquidity Provider account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-check-deposit-source-account": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Top up internal omnibus from Check Deposit Source account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-user-bank-account/{custodialAccountId}": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Top up internal omnibus from User Bank account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/{custodialAccountId}/non-api-clearing-account": {
   "put": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Configure non-API clearing account data on custodial account inside Fortress (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retrieve non-API clearing account data (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/from-ca-to-fiat-migration-account": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Create hidden payment to move fiat from an inactive provider specific to FortressTradeAndDepositFiatMigration account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/run-migration-job": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Run movementJob FromActivatedAccountToFiatOmnibusAccount or FromInactivatedAccountToFiatMigrationAccount (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/suspense/payments/{paymentId}/resolve": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Resolve payment on suspense account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/suspense/not-resolved-payments": {
   "get": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retrieve list transactions of not resolved payments on suspense account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/payments/process-stuck-payment": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retry or abort saga step that stuck (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/retry-transactions": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Retry trading for specified transactions. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/agreement": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Create custodial account agreement (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/payments/{paymentId}/funds-clawback": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Return funds from custodial account (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/{custodialAccountId}/replace-omnibus": {
   "put": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Replace omnibus account banking data (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/organizations/{organizationId}/settlement-accounts-configuration/{custodialAccountId}": {
   "put": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Configure settlement account for the specific list of assets per organization. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/organizations/{organizationId}/settlement-accounts-configuration": {
   "get": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Get settlement accounts configuration for the specified organization. (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/helper-account": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Create helper account (fortress accounts as omnibus complementary accounts) (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/process-transfer-manually": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Create a payment to store records about manually processed transfer (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/crypto-buy-refunds": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Refund internal from Liquidity Provider to end user custodial (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/crypto-sell-refunds": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Refund internal crypto from Liquidity Provider to end user custodial (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/from-ca-to-trading": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Refund internal crypto from end user custodial to Fortress Trading (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/from-ca-to-liquidity": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Refund internal crypto from user custodial to Fortress Liquidity (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/force-complete-transaction/{transactionId}": {
   "patch": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Force successful transaction completion for failed payment (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/custodial-accounts/from-trading-to-liquidity-provider": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Refund internal crypto from Fortress Trading to Liquidity Provider (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/invalidate-cache": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Invalidate cache immediately (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/import-tp-recon-payments/csv": {
   "post": {
    "tags": [
     "InternalAdmin"
    ],
    "summary": "Import file with payments to try find missing payments or link existing (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/manually-process/wire-withdrawal/{paymentId}/unlock-and-return-money": {
   "post": {
    "tags": [
     "ManuallyProcess"
    ],
    "summary": "Unlock and return money to user while wire withdrawal failing (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/manually-process/wire-withdrawal/{paymentId}/remove-locked-money-from-account": {
   "post": {
    "tags": [
     "ManuallyProcess"
    ],
    "summary": "Remove locked money from account in case wire withdrawal failing and processing manually through TP API (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/internal-admin/v1/manually-process/crypto-deposit/{paymentId}/move-pending-to-disbursable": {
   "post": {
    "tags": [
     "ManuallyProcess"
    ],
    "summary": "Move pending to disbursable in case crypto deposit failing (Auth policies: InternalAdmin)",
    "security": [
     {
      "Bearer": [
       "InternalAdmin"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Retrieve the organizations. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{organizationId}": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Retrieve the organization. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{orgId}/custody-providers-configurations": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Retrieve the custody providers configurations. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{orgId}/custody-providers-configurations/{assetType}": {
   "put": {
    "tags": [
     "Ops"
    ],
    "summary": "Add or update the configuration for particular asset type. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{orgId}/price-markup-configuration/{tradingPair}": {
   "put": {
    "tags": [
     "Ops"
    ],
    "summary": "Add or replace trading pair markup configuration (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{orgId}/price-markup-configuration": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get price markup for organization level and trading pair level (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Ops"
    ],
    "summary": "Configure price markup. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/fortress-payments-data/trades": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Return more details  about trades. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/fortress-payments-data/trades/{mainTransactionId}": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Return more detailed info about particular transfer. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/liquidity-provider-orders-data/orders": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Return more details  about orders. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/liquidity-provider-orders-data/orders/{id}": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Return more detailed info about particular order. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/close": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Close custodial account (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/fortress-wire-settlement/international-wires": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get international wires withdrawals info (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/fortress-wire-settlement/international-wires/{id}": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Update the status of an international wire payment and its corresponding main transaction (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/process-transfer-manually": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Create a payment to store records about manually processed transfer (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/crypto-buy-refunds": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Refund internal from Liquidity Provider to end user custodial (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/crypto-sell-refunds": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Refund internal crypto from Liquidity Provider to end user custodial (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/from-ca-to-trading": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Refund internal crypto from end user custodial to Fortress Trading (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/from-trading-to-liquidity-provider": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Refund internal crypto from Fortress Trading to Liquidity Provider (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/from-ca-to-liquidity": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Refund internal crypto from user custodial to Fortress Liquidity (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/force-complete-transaction/{transactionId}": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Force successful transaction completion for failed payment (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/retry-transactions": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Retry trading for specified transactions. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/transactions/{transactionId}/mt103": {
   "put": {
    "tags": [
     "Ops"
    ],
    "summary": "Add or replace MT103 reference for InternationalWireWithdrawal transaction (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get MT103 reference (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/organizations/{organizationId}/payment-approval-configuration": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Add or update payment approval configuration for organization. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get payment approval configuration for organization. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/transfers/precious-metals": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Admin endpoint for managing precious metals deposits/withdrawal (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/clearing-account-config/{organizationId}/{paymentType}": {
   "put": {
    "tags": [
     "Ops"
    ],
    "summary": "Set clearing accounts per organization (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Ops"
    ],
    "summary": "Delete clearing account for payment type per organization (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/clearing-account-config/{organizationId}": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get clearing accounts per organization (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Retrieve the filtered, paged list with custodial accounts. (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/suspend": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Suspend custodial account (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/resume": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Resume custodial account (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/import/csv": {
   "post": {
    "tags": [
     "Ops"
    ],
    "summary": "Import file with balances (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/fortress-payments-data/transactions/{transactionId}": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Get a list of transaction parts (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/non-api-clearing-account": {
   "get": {
    "tags": [
     "Ops"
    ],
    "summary": "Retrieve non-API clearing account data (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/update-cross-organization-account": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Update cross organization account (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/ops/v1/custodial-accounts/{custodialAccountId}/set-provider-cross-organization-account": {
   "patch": {
    "tags": [
     "Ops"
    ],
    "summary": "Set main provider specific accounts for cross organization accounts (Auth policies: Ops)",
    "security": [
     {
      "Bearer": [
       "Ops"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/ops-users": {
   "post": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Create the ops user. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Retrieve the ops users. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/ops-users/{id}": {
   "get": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Retrieve the ops user. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Patch the ops users. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/ops-users/{id}/password": {
   "put": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Update the ops user password. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/ops-users/{id}/roles": {
   "patch": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Setup roles for the ops users. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "OpsUsers"
    ],
    "summary": "Retrieve the ops user roles. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/v1/private-cross-service/organizations/{organizationId}/permissions": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organization."
   }
  },
  "/api/v1/private-cross-service/organizations/{organizationId}": {
   "get": {
    "tags": [
     "Organizations"
    ]
   }
  },
  "/api/v1/private-cross-service/organizations/{orgId}/crypto-price-markup-configuration/{tradingPair}": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Get crypto price markup configuration (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/organizations/{organizationId}/custody-provider-configuration": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve custody provider configuration."
   }
  },
  "/api/security-admin/v1/organizations": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organizations. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Organizations"
    ],
    "summary": "Create the organization. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/organizations/{organizationId}": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organization. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Organizations"
    ],
    "summary": "Patch the organizations. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/organizations/{organizationId}/roles": {
   "patch": {
    "tags": [
     "Organizations"
    ],
    "summary": "Setup roles for the organizations. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organization roles. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/organizations/{organizationId}/permissions": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organization permissions. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Organizations"
    ],
    "summary": "Patch the organization permissions. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/organizations/{organizationId}/password": {
   "put": {
    "tags": [
     "Organizations"
    ],
    "summary": "Update the organization password. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/security-admin/v1/organizations/{organizationId}/admin-configuration": {
   "get": {
    "tags": [
     "Organizations"
    ],
    "summary": "Retrieve the organization admin configuration. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Organizations"
    ],
    "summary": "Patch the organization admin configuration. (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/v1/private-cross-service/payments": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Create the payment."
   }
  },
  "/api/v1/private-cross-service/payments/{paymentId}": {
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "Retrieve the payment by id."
   }
  },
  "/api/v1/private-cross-service/payments/fiat": {
   "post": {
    "tags": [
     "Payments"
    ]
   }
  },
  "/api/v1/private-cross-service/payments/{paymentId}/approve": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Approve payment. Allowed only for Integration dashboard users."
   }
  },
  "/api/v1/private-cross-service/payments/{paymentId}/reject": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Reject payment. Allowed only for Integration dashboard users."
   }
  },
  "/api/trust/v1/payments": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Create the payment. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   },
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "Retrieve the filtered, paged list with payments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/payments/{paymentId}/cancel": {
   "put": {
    "tags": [
     "Payments"
    ],
    "summary": "Cancel payment, right now ACH payments cancelling supported only (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/payments/{paymentId}": {
   "get": {
    "tags": [
     "Payments"
    ],
    "summary": "Retrieve the payment by id. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/payments/{paymentId}/approve": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Approve payment. Allowed only for Integration dashboard users. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/payments/{paymentId}/reject": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Reject payment. Allowed only for Integration dashboard users. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/sub-accounts/payments": {
   "post": {
    "tags": [
     "Payments"
    ],
    "summary": "Create a payment for sub accounts. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/security-admin/v1/assets-to-allow-negative-balances": {
   "get": {
    "tags": [
     "SecurityAdmin"
    ],
    "summary": "Retrieve configuration of assets to allow negative balances (Auth policies: SecurityAdmin)",
    "security": [
     {
      "Bearer": [
       "SecurityAdmin"
      ]
     }
    ]
   }
  },
  "/api/trust/v1/sub-accounts/sandbox/{subAccountId}/start-incoming-wire": {
   "post": {
    "tags": [
     "SubAccounts"
    ],
    "summary": "Create an incoming wire simulation on sandbox environments. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/transactions": {
   "get": {
    "tags": [
     "Transactions"
    ],
    "summary": "Retrieve the filtered, paged list with transactions. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/trust/v1/transactions/{transactionId}": {
   "get": {
    "tags": [
     "Transactions"
    ],
    "summary": "Retrieve the transaction by id. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  },
  "/api/v1/private-cross-service/transfers": {
   "post": {
    "tags": [
     "Transfers"
    ],
    "summary": "Creates the transfer. The same signature and logic as in POST api/trust/v1/transfers.\r\nThis private endpoint is used by the Elements API to create transfers."
   }
  },
  "/api/trust/v1/transfers": {
   "post": {
    "tags": [
     "Transfers"
    ],
    "summary": "Execute transfer. (Auth)",
    "security": [
     {
      "Bearer": []
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "Bearer": {
    "type": "apiKey",
    "description": "Put access token in the box below.<br>For example: <b>Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I</b>",
    "name": "Authorization",
    "in": "header"
   }
  }
 },
 "security": [
  {
   "Bearer": []
  }
 ]
}