openapi: 3.0.1
info:
  title: Template Api
  version: '1.0'
servers:
  - url: 'https://api.sandbox.fortressapi.com/'
paths:
  /api/internal-admin/v1/custodial-accounts/agreement:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Create custodial account agreement (Auth policies: InternalAdmin)'
  /api/internal-admin/v1/custodial-accounts/crypto-buy-refunds:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Refund internal from Liquidity Provider to end user custodial (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/crypto-sell-refunds:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Refund internal crypto from Liquidity Provider to end user custodial
        (Auth policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/ensure-system-accounts:
    patch:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Ensure system custodial account (Auth policies: InternalAdmin)'
  /api/internal-admin/v1/custodial-accounts/from-ca-to-fiat-migration-account:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Create hidden payment to move fiat from an inactive provider specific to
        FortressTradeAndDepositFiatMigration account (Auth policies:
        InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/from-ca-to-liquidity:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Refund internal crypto from user custodial to Fortress Liquidity (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/from-ca-to-trading:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Refund internal crypto from end user custodial to Fortress Trading (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/from-trading-to-liquidity-provider:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Refund internal crypto from Fortress Trading to Liquidity Provider (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/helper-account:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Create helper account (fortress accounts as omnibus complementary
        accounts) (Auth policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/process-transfer-manually:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Create a payment to store records about manually processed transfer
        (Auth policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/run-migration-job:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Run movementJob FromActivatedAccountToFiatOmnibusAccount or
        FromInactivatedAccountToFiatMigrationAccount (Auth policies:
        InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/suspense/not-resolved-payments:
    get:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Retrieve list transactions of not resolved payments on suspense account
        (Auth policies: InternalAdmin)
  '/api/internal-admin/v1/custodial-accounts/suspense/payments/{paymentId}/resolve':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Resolve payment on suspense account (Auth policies: InternalAdmin)'
  /api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-check-deposit-source-account:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Top up internal omnibus from Check Deposit Source account (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-liquidity-provider-account:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Top up internal omnibus from Liquidity Provider account (Auth policies:
        InternalAdmin)
  '/api/internal-admin/v1/custodial-accounts/top-up-internal-omnibus-balance-from-user-bank-account/{custodialAccountId}':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Top up internal omnibus from User Bank account (Auth policies:
        InternalAdmin)
  '/api/internal-admin/v1/custodial-accounts/{custodialAccountId}/non-api-clearing-account':
    get:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Retrieve non-API clearing account data (Auth policies: InternalAdmin)'
    put:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Configure non-API clearing account data on custodial account inside
        Fortress (Auth policies: InternalAdmin)
  '/api/internal-admin/v1/custodial-accounts/{custodialAccountId}/replace-omnibus':
    put:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Replace omnibus account banking data (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/force-complete-transaction/{transactionId}':
    patch:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Force successful transaction completion for failed payment (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/import-tp-recon-payments/csv:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Import file with payments to try find missing payments or link existing
        (Auth policies: InternalAdmin)
  /api/internal-admin/v1/invalidate-cache:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Invalidate cache immediately (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/manually-process/crypto-deposit/{paymentId}/move-pending-to-disbursable':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - ManuallyProcess
      summary: >-
        Move pending to disbursable in case crypto deposit failing (Auth
        policies: InternalAdmin)
  '/api/internal-admin/v1/manually-process/wire-withdrawal/{paymentId}/remove-locked-money-from-account':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - ManuallyProcess
      summary: >-
        Remove locked money from account in case wire withdrawal failing and
        processing manually through TP API (Auth policies: InternalAdmin)
  '/api/internal-admin/v1/manually-process/wire-withdrawal/{paymentId}/unlock-and-return-money':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - ManuallyProcess
      summary: >-
        Unlock and return money to user while wire withdrawal failing (Auth
        policies: InternalAdmin)
  /api/internal-admin/v1/organizations:
    get:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Retrieve the organizations. (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/organizations/{organizationId}':
    get:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Retrieve the organization. (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/organizations/{organizationId}/custodial-account':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Create the new custodial account without age validation. (Auth policies:
        InternalAdmin)
  '/api/internal-admin/v1/organizations/{organizationId}/inactivate-provider-specific/{provider}':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Inactivate ProviderSpecific Accounts. (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/organizations/{organizationId}/settlement-accounts-configuration':
    get:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Get settlement accounts configuration for the specified organization.
        (Auth policies: InternalAdmin)
  '/api/internal-admin/v1/organizations/{organizationId}/settlement-accounts-configuration/{custodialAccountId}':
    put:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: >-
        Configure settlement account for the specific list of assets per
        organization. (Auth policies: InternalAdmin)
  /api/internal-admin/v1/payments/process-stuck-payment:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Retry or abort saga step that stuck (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/payments/{paymentId}/funds-clawback':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Return funds from custodial account (Auth policies: InternalAdmin)'
  /api/internal-admin/v1/retry-transactions:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Retry trading for specified transactions. (Auth policies: InternalAdmin)'
  /api/internal-admin/v1/sync-auth0:
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Sync all orgs metadata with Auth0. (Auth policies: InternalAdmin)'
  '/api/internal-admin/v1/{organizationId}/sync-auth0':
    post:
      security:
        - Bearer:
            - InternalAdmin
      tags:
        - InternalAdmin
      summary: 'Sync org metadata with Auth0. (Auth policies: InternalAdmin)'
  '/api/ops/v1/clearing-account-config/{organizationId}':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Get clearing accounts per organization (Auth policies: Ops)'
  '/api/ops/v1/clearing-account-config/{organizationId}/{paymentType}':
    delete:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Delete clearing account for payment type per organization (Auth
        policies: Ops)
    put:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Set clearing accounts per organization (Auth policies: Ops)'
  /api/ops/v1/custodial-accounts:
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Retrieve the filtered, paged list with custodial accounts. (Auth
        policies: Ops)
  /api/ops/v1/custodial-accounts/crypto-buy-refunds:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Refund internal from Liquidity Provider to end user custodial (Auth
        policies: Ops)
  /api/ops/v1/custodial-accounts/crypto-sell-refunds:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Refund internal crypto from Liquidity Provider to end user custodial
        (Auth policies: Ops)
  /api/ops/v1/custodial-accounts/from-ca-to-liquidity:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Refund internal crypto from user custodial to Fortress Liquidity (Auth
        policies: Ops)
  /api/ops/v1/custodial-accounts/from-ca-to-trading:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Refund internal crypto from end user custodial to Fortress Trading (Auth
        policies: Ops)
  /api/ops/v1/custodial-accounts/from-trading-to-liquidity-provider:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Refund internal crypto from Fortress Trading to Liquidity Provider (Auth
        policies: Ops)
  /api/ops/v1/custodial-accounts/process-transfer-manually:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Create a payment to store records about manually processed transfer
        (Auth policies: Ops)
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/close':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Close custodial account (Auth policies: Ops)'
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/non-api-clearing-account':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Retrieve non-API clearing account data (Auth policies: Ops)'
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/resume':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Resume custodial account (Auth policies: Ops)'
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/set-provider-cross-organization-account':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Set main provider specific accounts for cross organization accounts
        (Auth policies: Ops)
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/suspend':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Suspend custodial account (Auth policies: Ops)'
  '/api/ops/v1/custodial-accounts/{custodialAccountId}/update-cross-organization-account':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Update cross organization account (Auth policies: Ops)'
  '/api/ops/v1/force-complete-transaction/{transactionId}':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Force successful transaction completion for failed payment (Auth
        policies: Ops)
  /api/ops/v1/fortress-payments-data/trades:
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Return more details  about trades. (Auth policies: Ops)'
  '/api/ops/v1/fortress-payments-data/trades/{mainTransactionId}':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Return more detailed info about particular transfer. (Auth policies:
        Ops)
  '/api/ops/v1/fortress-payments-data/transactions/{transactionId}':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Get a list of transaction parts (Auth policies: Ops)'
  /api/ops/v1/fortress-wire-settlement/international-wires:
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Get international wires withdrawals info (Auth policies: Ops)'
  '/api/ops/v1/fortress-wire-settlement/international-wires/{id}':
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Update the status of an international wire payment and its corresponding
        main transaction (Auth policies: Ops)
  /api/ops/v1/import/csv:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Import file with balances (Auth policies: Ops)'
  /api/ops/v1/liquidity-provider-orders-data/orders:
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Return more details  about orders. (Auth policies: Ops)'
  '/api/ops/v1/liquidity-provider-orders-data/orders/{id}':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Return more detailed info about particular order. (Auth policies: Ops)'
  /api/ops/v1/organizations:
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Retrieve the organizations. (Auth policies: Ops)'
  '/api/ops/v1/organizations/{orgId}/custody-providers-configurations':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Retrieve the custody providers configurations. (Auth policies: Ops)'
  '/api/ops/v1/organizations/{orgId}/custody-providers-configurations/{assetType}':
    put:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Add or update the configuration for particular asset type. (Auth
        policies: Ops)
  '/api/ops/v1/organizations/{orgId}/price-markup-configuration':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Get price markup for organization level and trading pair level (Auth
        policies: Ops)
    put:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Configure price markup. (Auth policies: Ops)'
  '/api/ops/v1/organizations/{orgId}/price-markup-configuration/{tradingPair}':
    put:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Add or replace trading pair markup configuration (Auth policies: Ops)'
  '/api/ops/v1/organizations/{organizationId}':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Retrieve the organization. (Auth policies: Ops)'
  '/api/ops/v1/organizations/{organizationId}/payment-approval-configuration':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Get payment approval configuration for organization. (Auth policies:
        Ops)
    patch:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Add or update payment approval configuration for organization. (Auth
        policies: Ops)
  /api/ops/v1/retry-transactions:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Retry trading for specified transactions. (Auth policies: Ops)'
  '/api/ops/v1/transactions/{transactionId}/mt103':
    get:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: 'Get MT103 reference (Auth policies: Ops)'
    put:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Add or replace MT103 reference for InternationalWireWithdrawal
        transaction (Auth policies: Ops)
  /api/ops/v1/transfers/precious-metals:
    post:
      security:
        - Bearer:
            - Ops
      tags:
        - Ops
      summary: >-
        Admin endpoint for managing precious metals deposits/withdrawal (Auth
        policies: Ops)
  /api/organization/v1/current-organization:
    get:
      security:
        - Bearer: []
      tags:
        - CurrentOrganization
      summary: Retrieve the current organization. (Auth)
    patch:
      security:
        - Bearer: []
      tags:
        - CurrentOrganization
      summary: Update the current organization. (Auth)
  /api/organization/v1/current-organization/readonly:
    post:
      security:
        - Bearer: []
      tags:
        - CurrentOrganization
      summary: Create a read-only user. (Auth)
  /api/organization/v1/current-organization/webhook-config:
    get:
      security:
        - Bearer: []
      tags:
        - CurrentOrganization
      summary: Retrieve the webhook configuration. (Auth)
    patch:
      security:
        - Bearer: []
      tags:
        - CurrentOrganization
      summary: Patch the current webhook config. (Auth)
  /api/security-admin/v1/assets-to-allow-negative-balances:
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - SecurityAdmin
      summary: >-
        Retrieve configuration of assets to allow negative balances (Auth
        policies: SecurityAdmin)
  /api/security-admin/v1/endpoints-permissions-tree:
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - EndpointsPermissionsTree
      summary: >-
        Retrieve hierarchy of endpoint access permissions (Auth policies:
        SecurityAdmin)
  '/api/security-admin/v1/endpoints-permissions-tree/{id}':
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - EndpointsPermissionsTree
      summary: >-
        Patches endpoint access permission tree node (Auth policies:
        SecurityAdmin)
  /api/security-admin/v1/ops-users:
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Retrieve the ops users. (Auth policies: SecurityAdmin)'
    post:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Create the ops user. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/ops-users/{id}':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Retrieve the ops user. (Auth policies: SecurityAdmin)'
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Patch the ops users. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/ops-users/{id}/password':
    put:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Update the ops user password. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/ops-users/{id}/roles':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Retrieve the ops user roles. (Auth policies: SecurityAdmin)'
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - OpsUsers
      summary: 'Setup roles for the ops users. (Auth policies: SecurityAdmin)'
  /api/security-admin/v1/organizations:
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Retrieve the organizations. (Auth policies: SecurityAdmin)'
    post:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Create the organization. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/organizations/{organizationId}':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Retrieve the organization. (Auth policies: SecurityAdmin)'
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Patch the organizations. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/organizations/{organizationId}/admin-configuration':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: >-
        Retrieve the organization admin configuration. (Auth policies:
        SecurityAdmin)
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: >-
        Patch the organization admin configuration. (Auth policies:
        SecurityAdmin)
  '/api/security-admin/v1/organizations/{organizationId}/password':
    put:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Update the organization password. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/organizations/{organizationId}/permissions':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Retrieve the organization permissions. (Auth policies: SecurityAdmin)'
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Patch the organization permissions. (Auth policies: SecurityAdmin)'
  '/api/security-admin/v1/organizations/{organizationId}/roles':
    get:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Retrieve the organization roles. (Auth policies: SecurityAdmin)'
    patch:
      security:
        - Bearer:
            - SecurityAdmin
      tags:
        - Organizations
      summary: 'Setup roles for the organizations. (Auth policies: SecurityAdmin)'
  /api/trust/v1/assets:
    get:
      security:
        - Bearer: []
      tags:
        - Assets
      summary: Retrieve a list of assets for specific organization. (Auth)
    post:
      security:
        - Bearer: []
      tags:
        - Assets
      summary: Create the asset. (Auth)
  '/api/trust/v1/assets/{id}':
    get:
      security:
        - Bearer: []
      tags:
        - Assets
      summary: Retrieve the asset by id (Auth)
    patch:
      security:
        - Bearer: []
      tags:
        - Assets
      summary: Patch the asset. (Auth)
  /api/trust/v1/available-transfer-methods:
    get:
      security:
        - Bearer: []
      tags:
        - AvailableTransferMethods
      summary: Retrieve a list with available transfer methods. (Auth)
  /api/trust/v1/custodial-accounts:
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: 'Retrieve the filtered, paged list with custodial accounts. (Auth)'
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Create the new custodial account. (Auth)
  /api/trust/v1/custodial-accounts/agreement:
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Get custodial account agreement (Auth)
  /api/trust/v1/custodial-accounts/sandbox/start-incoming-wire-bulk:
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Create an incoming wire simulation on sandbox environments. (Auth)
  '/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-ach':
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Create an incoming ach simulation on sandbox environments. (Auth)
  '/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-ach-withdrawal':
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: >-
        Create an incoming ach withdrawal simulation on sandbox environments.
        (Auth)
  '/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-check':
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Create incoming check deposit simulation on sandbox environments. (Auth)
  '/api/trust/v1/custodial-accounts/sandbox/{custodialAccountId}/start-incoming-wire':
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Create an incoming wire simulation on sandbox environments. (Auth)
  '/api/trust/v1/custodial-accounts/{accountId}/beneficiaries':
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve the collection of account beneficiaries (Auth)
    put:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Overwrite beneficiaries for an account (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}':
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve the custodial account by id. (Auth)
    patch:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Update account status (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/balances':
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve the custodial account balances. (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/crypto-deposit-instructions/{network}/{assetFiatType}':
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve the crypto deposit instructions. (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/fiat-deposit-instructions/{assetFiatType}':
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve the fiat deposit instructions. (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/label':
    patch:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Update custodial account label (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/rename':
    patch:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Update account name (Auth)
  '/api/trust/v1/custodial-accounts/{custodialAccountId}/withdraw-crypto':
    post:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Withdraw crypto. (Auth)
  /api/trust/v1/external-accounts:
    get:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: 'Retrieve the filtered, paged list with external accounts. (Auth)'
  /api/trust/v1/external-accounts/financial:
    post:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: >-
        Create a funds transfer method and the respective external account.
        (Auth)
  '/api/trust/v1/external-accounts/financial/widget-url/{identityId}':
    get:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: Retrieve the widget Url for particular identity. (Auth)
  /api/trust/v1/external-accounts/international-wire:
    post:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: Create a new international wire (Auth)
  /api/trust/v1/external-accounts/wire:
    post:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: Create the external wire account. (Auth)
  '/api/trust/v1/external-accounts/{externalAccountId}':
    get:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: Retrieve specific external account by id. (Auth)
  /api/trust/v1/payments:
    get:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: 'Retrieve the filtered, paged list with payments. (Auth)'
    post:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Create the payment. (Auth)
  '/api/trust/v1/payments/{paymentId}':
    get:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Retrieve the payment by id. (Auth)
  '/api/trust/v1/payments/{paymentId}/approve':
    post:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Approve payment. Allowed only for Integration dashboard users. (Auth)
  '/api/trust/v1/payments/{paymentId}/cancel':
    put:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: 'Cancel payment, right now ACH payments cancelling supported only (Auth)'
  '/api/trust/v1/payments/{paymentId}/reject':
    post:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Reject payment. Allowed only for Integration dashboard users. (Auth)
  /api/trust/v1/sub-accounts/payments:
    post:
      security:
        - Bearer: []
      tags:
        - Payments
      summary: Create a payment for sub accounts. (Auth)
  '/api/trust/v1/sub-accounts/sandbox/{subAccountId}/start-incoming-wire':
    post:
      security:
        - Bearer: []
      tags:
        - SubAccounts
      summary: Create an incoming wire simulation on sandbox environments. (Auth)
  /api/trust/v1/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: 'Retrieve the filtered, paged list with transactions. (Auth)'
  '/api/trust/v1/transactions/{transactionId}':
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Retrieve the transaction by id. (Auth)
  /api/trust/v1/transfers:
    post:
      security:
        - Bearer: []
      tags:
        - Transfers
      summary: Execute transfer. (Auth)
  '/api/v1/private-cross-service/auth/default-auth-identifier/{orgId}':
    get:
      tags:
        - Auth
      summary: Retrieves auth identifier by organization id
  '/api/v1/private-cross-service/auth/enabled-endpoints-permissions-for-api-user/{authId}':
    get:
      tags:
        - Auth
      summary: Retrieve enabled endpoints permissions for api user
  /api/v1/private-cross-service/auth/endpoints-permissions-tree:
    get:
      tags:
        - Auth
      summary: Retrieve full tree of endpoints permissions
  /api/v1/private-cross-service/auth/global-enabled-endpoints-permissions:
    get:
      tags:
        - Auth
      summary: Retrieve global enabled endpoints permissions
  /api/v1/private-cross-service/custodial-accounts:
    get:
      security:
        - Bearer: []
      tags:
        - CustodialAccounts
      summary: Retrieve custodial accounts by identity identifier. (Auth)
    post:
      tags:
        - CustodialAccounts
      summary: Create the new custodial account.
  '/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}':
    get:
      tags:
        - CustodialAccounts
      summary: Retrieve the custodial account by its id.
    patch:
      tags:
        - CustodialAccounts
      summary: Update account status
  '/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/crypto-deposit-instructions/{network}/{assetFiatType}':
    get:
      tags:
        - CustodialAccounts
      summary: Retrieve the crypto deposit instructions.
  '/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/fiat-deposit-instructions/{assetFiatType}':
    get:
      tags:
        - CustodialAccounts
      summary: Retrieve the fiat deposit instructions.
  '/api/v1/private-cross-service/custodial-accounts/{custodialAccountId}/rename-with-label':
    patch:
      tags:
        - CustodialAccounts
      summary: Update account name and label.
  /api/v1/private-cross-service/external-accounts:
    get:
      security:
        - Bearer: []
      tags:
        - ExternalAccounts
      summary: Retrieve external accounts by identity identifier. (Auth)
  /api/v1/private-cross-service/external-accounts/international-wire:
    post:
      tags:
        - ExternalAccounts
      summary: Create a new international wire
  /api/v1/private-cross-service/external-accounts/wire:
    post:
      tags:
        - ExternalAccounts
      summary: Create the external wire account.
  '/api/v1/private-cross-service/organizations/{orgId}/crypto-price-markup-configuration/{tradingPair}':
    get:
      security:
        - Bearer: []
      tags:
        - Organizations
      summary: Get crypto price markup configuration (Auth)
  '/api/v1/private-cross-service/organizations/{organizationId}/custody-provider-configuration':
    get:
      tags:
        - Organizations
      summary: Retrieve custody provider configuration.
  '/api/v1/private-cross-service/organizations/{organizationId}/permissions':
    get:
      tags:
        - Organizations
      summary: Retrieve the organization.
  /api/v1/private-cross-service/payments:
    post:
      tags:
        - Payments
      summary: Create the payment.
  '/api/v1/private-cross-service/payments/{paymentId}':
    get:
      tags:
        - Payments
      summary: Retrieve the payment by id.
  '/api/v1/private-cross-service/payments/{paymentId}/approve':
    post:
      tags:
        - Payments
      summary: Approve payment. Allowed only for Integration dashboard users.
  '/api/v1/private-cross-service/payments/{paymentId}/reject':
    post:
      tags:
        - Payments
      summary: Reject payment. Allowed only for Integration dashboard users.
  /api/v1/private-cross-service/transfers:
    post:
      tags:
        - Transfers
      summary: "Creates the transfer. The same signature and logic as in POST api/trust/v1/transfers.\r\nThis private endpoint is used by the Elements API to create transfers."
components:
  securitySchemes:
    Bearer:
      description: >-
        Put access token in the box below. For example: <b>Bearer
        eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I</b>
      in: header
      name: Authorization
      type: apiKey
security:
  - Bearer: []