import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "payments/template-api",
    },
    {
      type: "category",
      label: "InternalAdmin",
      items: [
        {
          type: "doc",
          id: "payments/create-custodial-account-agreement-auth-policies-internal-admin",
          label: "Create custodial account agreement (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-from-liquidity-provider-to-end-user-custodial-auth-policies-internal-admin",
          label: "Refund internal from Liquidity Provider to end user custodial (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-liquidity-provider-to-end-user-custodial-auth-policies-internal-admin",
          label: "Refund internal crypto from Liquidity Provider to end user custodial (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/ensure-system-custodial-account-auth-policies-internal-admin",
          label: "Ensure system custodial account (Auth policies: InternalAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/create-hidden-payment-to-move-fiat-from-an-inactive-provider-specific-to-fortress-trade-and-deposit-fiat-migration-account-auth-policies-internal-admin",
          label: "Create hidden payment to move fiat from an inactive provider specific to FortressTradeAndDepositFiatMigration account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-user-custodial-to-fortress-liquidity-auth-policies-internal-admin",
          label: "Refund internal crypto from user custodial to Fortress Liquidity (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-end-user-custodial-to-fortress-trading-auth-policies-internal-admin",
          label: "Refund internal crypto from end user custodial to Fortress Trading (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-fortress-trading-to-liquidity-provider-auth-policies-internal-admin",
          label: "Refund internal crypto from Fortress Trading to Liquidity Provider (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-helper-account-fortress-accounts-as-omnibus-complementary-accounts-auth-policies-internal-admin",
          label: "Create helper account (fortress accounts as omnibus complementary accounts) (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-a-payment-to-store-records-about-manually-processed-transfer-auth-policies-internal-admin",
          label: "Create a payment to store records about manually processed transfer (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/run-movement-job-from-activated-account-to-fiat-omnibus-account-or-from-inactivated-account-to-fiat-migration-account-auth-policies-internal-admin",
          label: "Run movementJob FromActivatedAccountToFiatOmnibusAccount or FromInactivatedAccountToFiatMigrationAccount (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-list-transactions-of-not-resolved-payments-on-suspense-account-auth-policies-internal-admin",
          label: "Retrieve list transactions of not resolved payments on suspense account (Auth policies: InternalAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/resolve-payment-on-suspense-account-auth-policies-internal-admin",
          label: "Resolve payment on suspense account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/top-up-internal-omnibus-from-check-deposit-source-account-auth-policies-internal-admin",
          label: "Top up internal omnibus from Check Deposit Source account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/top-up-internal-omnibus-from-liquidity-provider-account-auth-policies-internal-admin",
          label: "Top up internal omnibus from Liquidity Provider account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/top-up-internal-omnibus-from-user-bank-account-auth-policies-internal-admin",
          label: "Top up internal omnibus from User Bank account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-non-api-clearing-account-data-auth-policies-internal-admin",
          label: "Retrieve non-API clearing account data (Auth policies: InternalAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/configure-non-api-clearing-account-data-on-custodial-account-inside-fortress-auth-policies-internal-admin",
          label: "Configure non-API clearing account data on custodial account inside Fortress (Auth policies: InternalAdmin)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/replace-omnibus-account-banking-data-auth-policies-internal-admin",
          label: "Replace omnibus account banking data (Auth policies: InternalAdmin)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/force-successful-transaction-completion-for-failed-payment-auth-policies-internal-admin",
          label: "Force successful transaction completion for failed payment (Auth policies: InternalAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/import-file-with-payments-to-try-find-missing-payments-or-link-existing-auth-policies-internal-admin",
          label: "Import file with payments to try find missing payments or link existing (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/invalidate-cache-immediately-auth-policies-internal-admin",
          label: "Invalidate cache immediately (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organizations-auth-policies-internal-admin",
          label: "Retrieve the organizations. (Auth policies: InternalAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-auth-policies-internal-admin",
          label: "Retrieve the organization. (Auth policies: InternalAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-new-custodial-account-without-age-validation-auth-policies-internal-admin",
          label: "Create the new custodial account without age validation. (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/inactivate-provider-specific-accounts-auth-policies-internal-admin",
          label: "Inactivate ProviderSpecific Accounts. (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/get-settlement-accounts-configuration-for-the-specified-organization-auth-policies-internal-admin",
          label: "Get settlement accounts configuration for the specified organization. (Auth policies: InternalAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/configure-settlement-account-for-the-specific-list-of-assets-per-organization-auth-policies-internal-admin",
          label: "Configure settlement account for the specific list of assets per organization. (Auth policies: InternalAdmin)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retry-or-abort-saga-step-that-stuck-auth-policies-internal-admin",
          label: "Retry or abort saga step that stuck (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/return-funds-from-custodial-account-auth-policies-internal-admin",
          label: "Return funds from custodial account (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retry-trading-for-specified-transactions-auth-policies-internal-admin",
          label: "Retry trading for specified transactions. (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/sync-all-orgs-metadata-with-auth-0-auth-policies-internal-admin",
          label: "Sync all orgs metadata with Auth0. (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/sync-org-metadata-with-auth-0-auth-policies-internal-admin",
          label: "Sync org metadata with Auth0. (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "ManuallyProcess",
      items: [
        {
          type: "doc",
          id: "payments/move-pending-to-disbursable-in-case-crypto-deposit-failing-auth-policies-internal-admin",
          label: "Move pending to disbursable in case crypto deposit failing (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/remove-locked-money-from-account-in-case-wire-withdrawal-failing-and-processing-manually-through-tp-api-auth-policies-internal-admin",
          label: "Remove locked money from account in case wire withdrawal failing and processing manually through TP API (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/unlock-and-return-money-to-user-while-wire-withdrawal-failing-auth-policies-internal-admin",
          label: "Unlock and return money to user while wire withdrawal failing (Auth policies: InternalAdmin)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Ops",
      items: [
        {
          type: "doc",
          id: "payments/get-clearing-accounts-per-organization-auth-policies-ops",
          label: "Get clearing accounts per organization (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/delete-clearing-account-for-payment-type-per-organization-auth-policies-ops",
          label: "Delete clearing account for payment type per organization (Auth policies: Ops)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "payments/set-clearing-accounts-per-organization-auth-policies-ops",
          label: "Set clearing accounts per organization (Auth policies: Ops)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-filtered-paged-list-with-custodial-accounts-auth-policies-ops",
          label: "Retrieve the filtered, paged list with custodial accounts. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/refund-internal-from-liquidity-provider-to-end-user-custodial-auth-policies-ops",
          label: "Refund internal from Liquidity Provider to end user custodial (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-liquidity-provider-to-end-user-custodial-auth-policies-ops",
          label: "Refund internal crypto from Liquidity Provider to end user custodial (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-user-custodial-to-fortress-liquidity-auth-policies-ops",
          label: "Refund internal crypto from user custodial to Fortress Liquidity (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-end-user-custodial-to-fortress-trading-auth-policies-ops",
          label: "Refund internal crypto from end user custodial to Fortress Trading (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/refund-internal-crypto-from-fortress-trading-to-liquidity-provider-auth-policies-ops",
          label: "Refund internal crypto from Fortress Trading to Liquidity Provider (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-a-payment-to-store-records-about-manually-processed-transfer-auth-policies-ops",
          label: "Create a payment to store records about manually processed transfer (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/close-custodial-account-auth-policies-ops",
          label: "Close custodial account (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retrieve-non-api-clearing-account-data-auth-policies-ops",
          label: "Retrieve non-API clearing account data (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/resume-custodial-account-auth-policies-ops",
          label: "Resume custodial account (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/set-main-provider-specific-accounts-for-cross-organization-accounts-auth-policies-ops",
          label: "Set main provider specific accounts for cross organization accounts (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/suspend-custodial-account-auth-policies-ops",
          label: "Suspend custodial account (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/update-cross-organization-account-auth-policies-ops",
          label: "Update cross organization account (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/force-successful-transaction-completion-for-failed-payment-auth-policies-ops",
          label: "Force successful transaction completion for failed payment (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/return-more-details-about-trades-auth-policies-ops",
          label: "Return more details  about trades. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/return-more-detailed-info-about-particular-transfer-auth-policies-ops",
          label: "Return more detailed info about particular transfer. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/get-a-list-of-transaction-parts-auth-policies-ops",
          label: "Get a list of transaction parts (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/get-international-wires-withdrawals-info-auth-policies-ops",
          label: "Get international wires withdrawals info (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-the-status-of-an-international-wire-payment-and-its-corresponding-main-transaction-auth-policies-ops",
          label: "Update the status of an international wire payment and its corresponding main transaction (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/import-file-with-balances-auth-policies-ops",
          label: "Import file with balances (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/return-more-details-about-orders-auth-policies-ops",
          label: "Return more details  about orders. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/return-more-detailed-info-about-particular-order-auth-policies-ops",
          label: "Return more detailed info about particular order. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organizations-auth-policies-ops",
          label: "Retrieve the organizations. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-custody-providers-configurations-auth-policies-ops",
          label: "Retrieve the custody providers configurations. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/add-or-update-the-configuration-for-particular-asset-type-auth-policies-ops",
          label: "Add or update the configuration for particular asset type. (Auth policies: Ops)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/get-price-markup-for-organization-level-and-trading-pair-level-auth-policies-ops",
          label: "Get price markup for organization level and trading pair level (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/configure-price-markup-auth-policies-ops",
          label: "Configure price markup. (Auth policies: Ops)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/add-or-replace-trading-pair-markup-configuration-auth-policies-ops",
          label: "Add or replace trading pair markup configuration (Auth policies: Ops)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-auth-policies-ops",
          label: "Retrieve the organization. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/get-payment-approval-configuration-for-organization-auth-policies-ops",
          label: "Get payment approval configuration for organization. (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/add-or-update-payment-approval-configuration-for-organization-auth-policies-ops",
          label: "Add or update payment approval configuration for organization. (Auth policies: Ops)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retry-trading-for-specified-transactions-auth-policies-ops",
          label: "Retry trading for specified transactions. (Auth policies: Ops)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/get-mt-103-reference-auth-policies-ops",
          label: "Get MT103 reference (Auth policies: Ops)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/add-or-replace-mt-103-reference-for-international-wire-withdrawal-transaction-auth-policies-ops",
          label: "Add or replace MT103 reference for InternationalWireWithdrawal transaction (Auth policies: Ops)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/admin-endpoint-for-managing-precious-metals-deposits-withdrawal-auth-policies-ops",
          label: "Admin endpoint for managing precious metals deposits/withdrawal (Auth policies: Ops)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "CurrentOrganization",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-current-organization-auth",
          label: "Retrieve the current organization. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-the-current-organization-auth",
          label: "Update the current organization. (Auth)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/create-a-read-only-user-auth",
          label: "Create a read-only user. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-webhook-configuration-auth",
          label: "Retrieve the webhook configuration. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-current-webhook-config-auth",
          label: "Patch the current webhook config. (Auth)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "SecurityAdmin",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-configuration-of-assets-to-allow-negative-balances-auth-policies-security-admin",
          label: "Retrieve configuration of assets to allow negative balances (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "EndpointsPermissionsTree",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-hierarchy-of-endpoint-access-permissions-auth-policies-security-admin",
          label: "Retrieve hierarchy of endpoint access permissions (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patches-endpoint-access-permission-tree-node-auth-policies-security-admin",
          label: "Patches endpoint access permission tree node (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "OpsUsers",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-ops-users-auth-policies-security-admin",
          label: "Retrieve the ops users. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-ops-user-auth-policies-security-admin",
          label: "Create the ops user. (Auth policies: SecurityAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-ops-user-auth-policies-security-admin",
          label: "Retrieve the ops user. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-ops-users-auth-policies-security-admin",
          label: "Patch the ops users. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/update-the-ops-user-password-auth-policies-security-admin",
          label: "Update the ops user password. (Auth policies: SecurityAdmin)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-ops-user-roles-auth-policies-security-admin",
          label: "Retrieve the ops user roles. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/setup-roles-for-the-ops-users-auth-policies-security-admin",
          label: "Setup roles for the ops users. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Organizations",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-organizations-auth-policies-security-admin",
          label: "Retrieve the organizations. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-organization-auth-policies-security-admin",
          label: "Create the organization. (Auth policies: SecurityAdmin)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-auth-policies-security-admin",
          label: "Retrieve the organization. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-organizations-auth-policies-security-admin",
          label: "Patch the organizations. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-admin-configuration-auth-policies-security-admin",
          label: "Retrieve the organization admin configuration. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-organization-admin-configuration-auth-policies-security-admin",
          label: "Patch the organization admin configuration. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/update-the-organization-password-auth-policies-security-admin",
          label: "Update the organization password. (Auth policies: SecurityAdmin)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-permissions-auth-policies-security-admin",
          label: "Retrieve the organization permissions. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-organization-permissions-auth-policies-security-admin",
          label: "Patch the organization permissions. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization-roles-auth-policies-security-admin",
          label: "Retrieve the organization roles. (Auth policies: SecurityAdmin)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/setup-roles-for-the-organizations-auth-policies-security-admin",
          label: "Setup roles for the organizations. (Auth policies: SecurityAdmin)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/get-crypto-price-markup-configuration-auth",
          label: "Get crypto price markup configuration (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-custody-provider-configuration",
          label: "Retrieve custody provider configuration.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-organization",
          label: "Retrieve the organization.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Assets",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-a-list-of-assets-for-specific-organization-auth",
          label: "Retrieve a list of assets for specific organization. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-asset-auth",
          label: "Create the asset. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-asset-by-id-auth",
          label: "Retrieve the asset by id (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/patch-the-asset-auth",
          label: "Patch the asset. (Auth)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "AvailableTransferMethods",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-a-list-with-available-transfer-methods-auth",
          label: "Retrieve a list with available transfer methods. (Auth)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "CustodialAccounts",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-filtered-paged-list-with-custodial-accounts-auth",
          label: "Retrieve the filtered, paged list with custodial accounts. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-new-custodial-account-auth",
          label: "Create the new custodial account. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/get-custodial-account-agreement-auth",
          label: "Get custodial account agreement (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-an-incoming-wire-simulation-on-sandbox-environments-auth",
          label: "Create an incoming wire simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-an-incoming-ach-simulation-on-sandbox-environments-auth",
          label: "Create an incoming ach simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-an-incoming-ach-withdrawal-simulation-on-sandbox-environments-auth",
          label: "Create an incoming ach withdrawal simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-incoming-check-deposit-simulation-on-sandbox-environments-auth",
          label: "Create incoming check deposit simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-an-incoming-wire-simulation-on-sandbox-environments-auth",
          label: "Create an incoming wire simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-collection-of-account-beneficiaries-auth",
          label: "Retrieve the collection of account beneficiaries (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/overwrite-beneficiaries-for-an-account-auth",
          label: "Overwrite beneficiaries for an account (Auth)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-custodial-account-by-id-auth",
          label: "Retrieve the custodial account by id. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-account-status-auth",
          label: "Update account status (Auth)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-custodial-account-balances-auth",
          label: "Retrieve the custodial account balances. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-crypto-deposit-instructions-auth",
          label: "Retrieve the crypto deposit instructions. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-fiat-deposit-instructions-auth",
          label: "Retrieve the fiat deposit instructions. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-custodial-account-label-auth",
          label: "Update custodial account label (Auth)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/update-account-name-auth",
          label: "Update account name (Auth)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/withdraw-crypto-auth",
          label: "Withdraw crypto. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-custodial-accounts-by-identity-identifier-auth",
          label: "Retrieve custodial accounts by identity identifier. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-new-custodial-account",
          label: "Create the new custodial account.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-custodial-account-by-its-id",
          label: "Retrieve the custodial account by its id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-account-status",
          label: "Update account status",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-crypto-deposit-instructions",
          label: "Retrieve the crypto deposit instructions.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-fiat-deposit-instructions",
          label: "Retrieve the fiat deposit instructions.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/update-account-name-and-label",
          label: "Update account name and label.",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "ExternalAccounts",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-filtered-paged-list-with-external-accounts-auth",
          label: "Retrieve the filtered, paged list with external accounts. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-a-funds-transfer-method-and-the-respective-external-account-auth",
          label: "Create a funds transfer method and the respective external account. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-widget-url-for-particular-identity-auth",
          label: "Retrieve the widget Url for particular identity. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-a-new-international-wire-auth",
          label: "Create a new international wire (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-the-external-wire-account-auth",
          label: "Create the external wire account. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-specific-external-account-by-id-auth",
          label: "Retrieve specific external account by id. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-external-accounts-by-identity-identifier-auth",
          label: "Retrieve external accounts by identity identifier. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-a-new-international-wire",
          label: "Create a new international wire",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-the-external-wire-account",
          label: "Create the external wire account.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Payments",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-filtered-paged-list-with-payments-auth",
          label: "Retrieve the filtered, paged list with payments. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/create-the-payment-auth",
          label: "Create the payment. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-payment-by-id-auth",
          label: "Retrieve the payment by id. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/approve-payment-allowed-only-for-integration-dashboard-users-auth",
          label: "Approve payment. Allowed only for Integration dashboard users. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/cancel-payment-right-now-ach-payments-cancelling-supported-only-auth",
          label: "Cancel payment, right now ACH payments cancelling supported only (Auth)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "payments/reject-payment-allowed-only-for-integration-dashboard-users-auth",
          label: "Reject payment. Allowed only for Integration dashboard users. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-a-payment-for-sub-accounts-auth",
          label: "Create a payment for sub accounts. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/create-the-payment",
          label: "Create the payment.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-payment-by-id",
          label: "Retrieve the payment by id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/approve-payment-allowed-only-for-integration-dashboard-users",
          label: "Approve payment. Allowed only for Integration dashboard users.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/reject-payment-allowed-only-for-integration-dashboard-users",
          label: "Reject payment. Allowed only for Integration dashboard users.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "SubAccounts",
      items: [
        {
          type: "doc",
          id: "payments/create-an-incoming-wire-simulation-on-sandbox-environments-auth",
          label: "Create an incoming wire simulation on sandbox environments. (Auth)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Transactions",
      items: [
        {
          type: "doc",
          id: "payments/retrieve-the-filtered-paged-list-with-transactions-auth",
          label: "Retrieve the filtered, paged list with transactions. (Auth)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-the-transaction-by-id-auth",
          label: "Retrieve the transaction by id. (Auth)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Transfers",
      items: [
        {
          type: "doc",
          id: "payments/execute-transfer-auth",
          label: "Execute transfer. (Auth)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "payments/creates-the-transfer-the-same-signature-and-logic-as-in-post-api-trust-v-1-transfers-this-private-endpoint-is-used-by-the-elements-api-to-create-transfers",
          label: "Creates the transfer. The same signature and logic as in POST api/trust/v1/transfers.\r\nThis private endpoint is used by the Elements API to create transfers.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "payments/retrieves-auth-identifier-by-organization-id",
          label: "Retrieves auth identifier by organization id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-enabled-endpoints-permissions-for-api-user",
          label: "Retrieve enabled endpoints permissions for api user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-full-tree-of-endpoints-permissions",
          label: "Retrieve full tree of endpoints permissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/retrieve-global-enabled-endpoints-permissions",
          label: "Retrieve global enabled endpoints permissions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Identities",
      items: [
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "payments/",
          label: "Missing summary",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
